# Exemple d'entités Home Assistant créées automatiquement par ESPHome
# après intégration du firmware smartevse-sensorbox

sensor:
  - platform: template
    sensors:
      energie_soutiree:
        friendly_name: "Energie soutirée (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_energie_soutiree') }}"
        unit_of_measurement: "Wh"

      puissance_apparente_totale:
        friendly_name: "Puissance apparente totale (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_puissance_apparente_totale') }}"
        unit_of_measurement: "VA"

      courant_phase_1:
        friendly_name: "Courant Phase 1 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_courant_phase_1') }}"
        unit_of_measurement: "A"

      courant_phase_2:
        friendly_name: "Courant Phase 2 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_courant_phase_2') }}"
        unit_of_measurement: "A"

      courant_phase_3:
        friendly_name: "Courant Phase 3 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_courant_phase_3') }}"
        unit_of_measurement: "A"

      tension_phase_1:
        friendly_name: "Tension Phase 1 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_tension_phase_1') }}"
        unit_of_measurement: "V"

      tension_phase_2:
        friendly_name: "Tension Phase 2 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_tension_phase_2') }}"
        unit_of_measurement: "V"

      tension_phase_3:
        friendly_name: "Tension Phase 3 (Linky)"
        value_template: "{{ states('sensor.smartevse_sensorbox_tension_phase_3') }}"
        unit_of_measurement: "V"

      ct_total_current:
        friendly_name: "Courant total (CT)"
        value_template: "{{ states('sensor.smartevse_sensorbox_ct_total_current') }}"
        unit_of_measurement: "A"

      ct_total_power:
        friendly_name: "Puissance totale (CT)"
        value_template: "{{ states('sensor.smartevse_sensorbox_ct_total_power') }}"
        unit_of_measurement: "W"

      wifi_mode:
        friendly_name: "Mode WiFi SensorBox"
        value_template: "{{ states('sensor.smartevse_sensorbox_wifi_mode') }}"
