esphome:
  name: smartevse-sensorbox
  platform: ESP32
  board: esp32-s3-devkitc-1

# -------------------------------
# External components
# -------------------------------
external_components:
  - source: github://tgrauss/esphome-smartevse-sensorbox-linky
    components: [smartevse_sensorbox, smartevse_modbus, modbus_server]
    refresh: 0s

# -------------------------------
# I²C pour ADS1115 (CT)
# -------------------------------
i2c:
  sda: GPIO6
  scl: GPIO5
  scan: true

ads1115:
  - id: ads1115_ct
    address: 0x48

# -------------------------------
# UARTs
# -------------------------------
uart:
  - id: uart_tic
    rx_pin: GPIO44
    baud_rate: 9600
    parity: EVEN
    data_bits: 7
    stop_bits: 1

  - id: uart_smartevse
    tx_pin: GPIO11
    rx_pin: GPIO13
    baud_rate: 9600

  - id: uart_esphome
    tx_pin: GPIO7
    rx_pin: GPIO9
    baud_rate: 9600

# -------------------------------
# Teleinfo (TIC Linky)
# -------------------------------
teleinfo:
  id: linky_tic
  uart_id: uart_tic
  update_interval: 2s
  historical_mode: false

sensor:
  - platform: teleinfo
    tag_name: "EAST"
    id: east
    name: "Energie soutirée"
    unit_of_measurement: "Wh"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "SINSTS"
    id: sinsts
    name: "Puissance apparente totale"
    unit_of_measurement: "VA"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS1"
    id: irms1
    name: "Courant phase 1"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS2"
    id: irms2
    name: "Courant phase 2"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS3"
    id: irms3
    name: "Courant phase 3"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS1"
    id: urms1
    name: "Tension phase 1"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS2"
    id: urms2
    name: "Tension phase 2"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS3"
    id: urms3
    name: "Tension phase 3"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

# -------------------------------
# Deux serveurs Modbus
# -------------------------------
modbus_server:
  - id: mb_smartevse
    uart_id: uart_smartevse
    enable_pin: GPIO12
    address: 10
    baud_rate: 9600

  - id: mb_esphome
    uart_id: uart_esphome
    enable_pin: GPIO8
    address: 100
    baud_rate: 9600

# -------------------------------
# Composant SensorBox
# -------------------------------
smartevse_sensorbox:
  id: sensorbox
  ct_phase_a: ct_a_in
  ct_phase_b: ct_b_in
  ct_phase_c: ct_c_in
  ads_ref: ads_ref_in
  linky_power: sinsts
  linky_energy: east
  linky_current_l1: irms1
  linky_current_l2: irms2
  linky_current_l3: irms3
  linky_voltage_l1: urms1
  linky_voltage_l2: urms2
  linky_voltage_l3: urms3
  nominal_voltage: 230
  power_factor: 0.95
  three_phase: true
  prefer_linky_power: true
  autocalibration: true
  rotation: 0
  wire_mode: 1
  wifi_mode: 1
  update_interval: 1s

# -------------------------------
# Mapping Modbus vers SmartEVSE
# -------------------------------
smartevse_modbus:
  modbus_server_id: mb_smartevse
  sensorbox_id: sensorbox
  profile: smartevse_v2

# -------------------------------
# Mapping Modbus vers autre maître ESPHome
# -------------------------------
smartevse_modbus:
  modbus_server_id: mb_esphome
  sensorbox_id: sensorbox
  profile: linky_modbus
