esphome:
  name: sensorbox
  friendly_name: sensorbox

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf


external_components:
  - source: github://tgrauss/esphome-smartevse-sensorbox-linky
    components: [smartevse_sensorbox, modbus_server]
    refresh: 0s

logger:
  level: NONE
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 8.5

ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Ethernet pour ESP32-S3-ETH (désactiver wifi ci-dessus)
# ethernet:
#   type: W5500
#   clk_pin: GPIO13
#   mosi_pin: GPIO11
#   miso_pin: GPIO12
#   cs_pin: GPIO14
#   reset_pin: GPIO9
#   interrupt_pin: GPIO10

#api:
  # Don't reboot if the HomeAssistant connection times out (we can do just fine without it)
#  reboot_timeout: 0s
#  batch_delay: 50ms
#  encryption:
#    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

mdns:
  disabled: false

time:
  - platform: sntp
    timezone: Europe/Paris
    id: my_time

# I2C pour ADS1115
i2c:
  # ESP32-S3-Zero
  sda: GPIO6
  scl: GPIO5
  # ESP32-S3-ETH (PoE)
  # sda: GPIO1
  # scl: GPIO2
  scan: true

ads1115:
  - id: ads1115_ct
    address: 0x48

# UART TIC Linky
uart:
  - id: uart_tic
    rx_pin: GPIO44
    baud_rate: 9600
    parity: EVEN
    data_bits: 7
    stop_bits: 1

teleinfo:
  id: linky_tic
  uart_id: uart_tic
  update_interval: 2s
  historical_mode: false

# UART SmartEVSE RS485
uart:
  - id: uart_smartevse
    # ESP32-S3-Zero
    tx_pin: GPIO11
    rx_pin: GPIO13
    # ESP32-S3-ETH
    # tx_pin: GPIO40
    # rx_pin: GPIO42
    baud_rate: 9600

# UART ESPHome RS485
uart:
  - id: uart_esphome
    # ESP32-S3-Zero
    tx_pin: GPIO7
    rx_pin: GPIO9
    # ESP32-S3-ETH
    # tx_pin: GPIO37
    # rx_pin: GPIO39
    baud_rate: 9600

modbus_server:
  - id: mb_smartevse
    uart_id: uart_smartevse
    # ESP32-S3-Zero
    enable_pin: GPIO12
    # ESP32-S3-ETH
    # enable_pin: GPIO41
    address: 10
    baud_rate: 9600

  - id: mb_esphome
    uart_id: uart_esphome
    # ESP32-S3-Zero
    enable_pin: GPIO8
    # ESP32-S3-ETH
    # enable_pin: GPIO38
    address: 100
    baud_rate: 9600

smartevse_sensorbox:
  id: sensorbox
  ads1115_id: ads1115_ct
  teleinfo_id: linky_tic
  modbus_smartevse_id: mb_smartevse
  modbus_esphome_id: mb_esphome
  three_phase: false
  prefer_linky_power: true
  rotation: 0
  wire_mode: 1
  wifi_mode: 1   # mettre 0 si ETH
  ct_gain_a: 1.0
  ct_gain_b: 1.0
  ct_gain_c: 1.0
  ct_offset_a: 0.0
  ct_offset_b: 0.0
  ct_offset_c: 0.0
  ads_ref_voltage: 1.0
  nominal_voltage: 230.0
  power_factor: 0.95
  fast_interval_ms: 1000
  slow_interval_ms: 2000


# Désactiver si utilise esp32-s3-ethe (POE)
sensor:
  - platform: wifi_signal
    name: "WiFi Level"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"
