esphome:
  name: sensorbox
  friendly_name: sensorbox

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# -------------------------------
# External components
# -------------------------------
external_components:
  - source: github://tgrauss/esphome-smartevse-sensorbox-linky
    components: [smartevse_sensorbox, smartevse_modbus, modbus_server]
    refresh: 0s

logger:
  level: NONE
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 8.5

  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

 -------------------------------
# Ethernet W5500 (ESP32-S3-ETH PoE)
# -------------------------------
#ethernet:
#  type: W5500
#  clk_pin: GPIO13   # SCLK
#  mosi_pin: GPIO11  # MOSI
#  miso_pin: GPIO12  # MISO
#  cs_pin: GPIO14    # CS
#  reset_pin: GPIO9  # RST
#  interrupt_pin: GPIO10  # INT

api:
  # Don't reboot if the HomeAssistant connection times out (we can do just fine without it)
  reboot_timeout: 0s
  batch_delay: 50ms
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

mdns:
  disabled: false

time:
  - platform: sntp
    timezone: Europe/Paris
    id: my_time

# -------------------------------
# I²C pour ADS1115 (CT)
# -------------------------------
i2c:
  # ESP32-S3-Zero
  sda: GPIO6
  scl: GPIO5
  # ESP32-S3-ETH (PoE)
  # sda: GPIO1
  # scl: GPIO2
  scan: true

ads1115:
  - id: ads1115_ct
    address: 0x48

# -------------------------------
# UARTs
# -------------------------------
uart:
  # UART TIC Linky (direct on GPIO44 in 7E1)
  - id: uart_tic
    rx_pin: GPIO44
    baud_rate: 9600
    parity: EVEN
    data_bits: 7
    stop_bits: 1

  # UART for SmartEVSE (RS485, ESP32 slave)
  - id: uart_smartevse
    # ESP32-S3-Zero
    tx_pin: GPIO11
    rx_pin: GPIO13
    # ESP32-S3-ETH (PoE)
    # tx_pin: GPIO40
    # rx_pin: GPIO42
    baud_rate: 9600

  # UART for Modbus slave (other ESPHome/masters)
  - id: uart_esphome
    # ESP32-S3-Zero
    tx_pin: GPIO7
    rx_pin: GPIO9
    # ESP32-S3-ETH (PoE)
    # tx_pin: GPIO37
    # rx_pin: GPIO39
    baud_rate: 9600


# -------------------------------
# Teleinfo (TIC Linky)
# -------------------------------
teleinfo:
  id: linky_tic
  uart_id: uart_tic
  update_interval: 2s
  historical_mode: false

sensor:
  - platform: teleinfo
    tag_name: "EAST"
    id: east
    name: "Energie soutirée"
    unit_of_measurement: "Wh"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "SINSTS"
    id: sinsts
    name: "Puissance apparente totale"
    unit_of_measurement: "VA"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS1"
    id: irms1
    name: "Courant phase 1"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS2"
    id: irms2
    name: "Courant phase 2"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "IRMS3"
    id: irms3
    name: "Courant phase 3"
    unit_of_measurement: "A"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS1"
    id: urms1
    name: "Tension phase 1"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS2"
    id: urms2
    name: "Tension phase 2"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

  - platform: teleinfo
    tag_name: "URMS3"
    id: urms3
    name: "Tension phase 3"
    unit_of_measurement: "V"
    teleinfo_id: linky_tic

# -------------------------------
# Deux serveurs Modbus
# -------------------------------
modbus_server:
  - id: mb_smartevse
    uart_id: uart_smartevse
    # ESP32-S3-Zero
    enable_pin: GPIO12
    # ESP32-S3-ETH (PoE)
    # enable_pin: GPIO41
    address: 10
    baud_rate: 9600

  - id: mb_esphome
    uart_id: uart_esphome
    # ESP32-S3-Zero
    enable_pin: GPIO8
    # ESP32-S3-ETH (PoE)
    # enable_pin: GPIO38
    address: 100
    baud_rate: 9600



# -------------------------------
# Composant SensorBox
# -------------------------------
smartevse_sensorbox:
  id: sensorbox
  ct_phase_a: ct_a_in
  ct_phase_b: ct_b_in
  ct_phase_c: ct_c_in
  ads_ref: ads_ref_in
  linky_power: sinsts
  linky_energy: east
  linky_current_l1: irms1
  linky_current_l2: irms2
  linky_current_l3: irms3
  linky_voltage_l1: urms1
  linky_voltage_l2: urms2
  linky_voltage_l3: urms3
  nominal_voltage: 230
  power_factor: 0.95
  three_phase: true
  prefer_linky_power: true
  autocalibration: true
  rotation: 0
  wire_mode: 1
  wifi_mode: 1
  update_interval: 1s

# -------------------------------
# Mapping Modbus vers SmartEVSE
# -------------------------------
smartevse_modbus:
  modbus_server_id: mb_smartevse
  sensorbox_id: sensorbox
  profile: smartevse_v2

# -------------------------------
# Mapping Modbus vers autre maître ESPHome
# -------------------------------
smartevse_modbus:
  modbus_server_id: mb_esphome
  sensorbox_id: sensorbox
  profile: linky_modbus


sensor:
  - platform: wifi_signal
    name: "WiFi Level"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"

